import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="w-screen h-screen bg-auth-bg bg-cover bg-center">
      {children}
    </div>
  );
}
